export const Strings = {
  TEXTTITLE:{
  WELCOME:"Welcome to",
  HOME:"Home",
  CATEGORIESS:"Categories",
  ACCOUNT:"Don't you have an account? ",
  SIGNUPNOW:"Sign up now!",
  REMEBERME:"Remember me",
  FORGOTPWD:"Forgot Password?",
  NOTE:"Note to doctor",
  SIGNUPP:"Sign up",
  EDITPROFILE:"Edit Profile",
  ADD1:"Add Address",
  ADD2:"Add Card",
  UPDATE:"Update",
  INVITEFRIENDS:"Invite Friends",
  ADDTOBAG:"Add to Bag",
  SIGNIN:"Sign in",
  SIGNIN1:"Sign Up",
  LOGIN1:"Log in",
  OR:"OR",
  BYLIFELINE:"By using Lifeline,you agree to the ",
  TERMS:"Terms & Conditions",
  SIGNUPTITLE:"Sign up to",  
  ALREADYACCOUNT:"Already have an account? ",
  READYACCOUNT:"Don't have an account?",
  UNIQUEPWD:"Please enter a new unique password for email@email.com",
  PWDDESCRIPTION:"Please enter your register email ID.", 
  OTPDESCRIPTION:"Please enter the verification code.",
  PWDDESCRIPTION1:"We will send a verification code to your registered email ID.", 
  OTPDESCRIPTION1:"We have send a verification code to your registered email ID.",
  LOGINNOW:"Signup",
  SIGNUP:"Sign Up Account",
  NEXT:"Next",
  GET:"Get Started",
  RESETPWD:"Reset Password",
  FORGOTPWDTITLE:"Forget Password",
  YOUALREADY:"You are all ready!",
  SUCCESSDESC:"You're successfully registered an account",
  RETURNLOGIN:"Click Below to return to login.",
  BACKTOLOGIN:"Back to login",
  SIXDIGITCODE:"Please check your email inbox for the 6-digit code.",
  COMPLETEREG:"Complete Registration",
  EMAILVERIFICATION:"Email Verification",
  SCHEDULEAPPTTITLE:"Schedule An Appointment",
  CALENDERAPPTTITLE:"Pick a date & time",
  NAME:"Dr.Dimitri Petrenko",
  PROFESSION:"General practioner",
  CONFIRMAPPOINTMENT:"Confirm Appointment",
  YEAR:"July2020",
  TIME:"Time",
  SCHEDULE:"Schedule An Appointment",
  SCHEDULEAPPTCONTENT:"Connect with a General Practitioner at a later time & date. ",
  CHOOSEDOCTOR:"Choose doctor",
  SELECTPATIENTTITLE:"Select Patient",
  SELECTPATIENTCONTENT:"To better serve the right patient needs and accomdation,please select the patient who will be attending the video call",
  NEWPATIENTID:"New patient identity",
  NEWDESCID:"Please upload a photo of the patient's ID or",
  NEWPASSPORT:"passport for verification purpose",
  IMPORTPICTURE:"Successfully imported picture",
  COMPLETEPATIENT:"Complete patient details and consult doctor",
  CONFIRMDES:"Confirm",
  VIDEOCALLWITHDOCTORTITLE:"Video call with doctor",
  VIDEOCALLWITHDOCTORCONTENT:"Connect with a General Practitioner",
  ADDNEWPATIENTTITLE:"Add a new patient",
  FISH:"Fish",
  PRAWN:"Prawn",
  CROP:"Crop",
  PRICE:"Price :",
  WEIGHT:"Weight :",
  FILTER:"Filter",
  WHITEPOM:"White Pomfret1",
  RESET:"Reset",
  FISHES:"Fishes",
  AMOUNT:"50 items",
  ADDNEWPATIENTCONTENT:"We require you to upload a photo of the ID or passport of the patient and all the necessary Information required.",
  WHY:"Why?",
  WHYCONTENT:"Our healthcare regulations require this in order for the clinic to provide with preceiption medical certificate or referral.",
  ISITSECURE:"Is it secure?",
  ISITSECURECONTENT:"Yes! Not to worry, all of your information will be kept secure and confidential.",
  CONTINUEBUTTON:"Continue",
  VIDEOCALLCONSULTATION:"Video Call Consultation",
  CONSULT:"Consult Now",
  SCHEDULEAPPT:"Schedule Appointment",
  GENERALPRACTITIONER:"General Practitioner",
  ONLINESTORE:"Online Store",
  NEWARRIVALS:"New Arrivals",
  MORE:"More >",
  VIEWALL:"View All",
  NEWS:"News",
  NEWPATIENTITITLE:"New Patient information",
  NEWPATIENTCONTENT:"Please provide accurate information of the new patient. As this is vital for our doctor to precribe and monitor patients.",
  NEWPATIENTVERIFY:"Proceed to verify your number",
  FULLNAME:"Full Name",
  NRIC:"NRIC/Passport Number",
  COUNTRYOFCITIZENSHIP:"Country of citizenship",
  RELATIVE:"Relative",
  GENDER:"Gender",
  DOB:"Date of birth",
  RESIDENTALADDRESS:"Residental Address",
  POSTALCODE:"Postal code",
  COUNTRY:"Country",
  SCHEDULEMAINTITLE:"Schedule",
  UPCOMINGAPPOINTMENT:"Upcoming Appointments",
  HISTORY:"History",
  PATIENTPROFILETITLE:"Patient Profiles",
  CATEGORIEES:"Categories",
  CATEGORIEESS:"Categories :",
  ADDNEWPATIENTTITLE:"Add a new patient",
  WAITINGYOURTURN:"Waiting your turn",
  WAITINGCONTENT1:"Please Kindly wait as your chosen doctor is",
  WAITINGCONTENT2:"currently consulting someone else, every",
  WAITINGCONTENT3:"patient is carefully examined to ensure the",
  WAITINGCONTENT4:"highest quality of service.",
  HOWLONGQUE:"How long does it usually take?",
  HOWLONGANS:"Each patient usually take up to 10mins, to ensure enough time for doctor to evaluate and prescribe the right medication for each individual.",
  EXITQUEUE:"Exit Queue",
  FINDINGDR:"Finding you a doctor" ,
  DOCTORFOUND:"Doctor found!",
  FINDINGCONTENT1:"Please Kindly wait as we're trying our best to",
  FINDINGCONTENT2:"help match you with the fastest available",
  FINDINGCONTENT3:"doctor at the moment.",
  EXIT:"Exit",
  DRHOWLONGANS:"Usually it takes less than 5 mins to get you a doctor.it might be longer due to unforseen circumstance or peak hour.",
  UNFINDINGDR:"Doctor unavailable" ,
  FINDDOCTOR:"Find doctors",
  UNFINDINGDRCONTENT:"Unfortunately the doctor at the moment is not available to take your consultation",
  UNFINDINGDRCONTENT1:"Pick other doctors or choose \"Fastest Available\" to quickly find an available doctor for your consultation!",
  DOCTORFOUNDCONTENT1:"The doctor will call you shortly.",
  DOCTORFOUNDCONTENT2:"Please hold while the doctor is preparing",
  DOCTORFOUNDCONTENT3:"and/or going through your details"

  },
  HISTORYTEXT:{
    HISTORY:"History",
    DCTNAME:"Dr. Dimitri Petrenko",
    NAME:"Name:",
    DETAIL:"Detail",
    GENERALPRACTITIONER:"General Practitioner",
    ID:"ID#1053",
    CONSULATION:"Consultation",
    MEDICATION:"Medication Prescribed",
    CONTACTDCT:"Contact Doctor:",
    SUBJECT:"Subject",
    MSG:"Message",
    CREATETICKET:"Create Ticket",
    MEDICAL:"Medical Certificate",
    INVOICE:"Invoice",
    CANCELLED:"Cancelled",
    CANCELLEDCONTENT:"Appointment cancelled by user.",
    CANCELLATION:"You'll not be billed for this cancellation. "
  },
  VERIFYNUMBERTEXT:{
    VERIFY:"Verify Your Number",
    VERIFYCONTENT:"Please enter the 4 Digit code that sent to your phone recently.",
    RESEND:"Resend",
    PROCEED:"Proceed to upload your ID or Passport",
    CONFORM:"Confirm"
    },
    TERMSANDCONDITIONS:{
  TITLE:"We are part of the MOH regulatory Sandbox",
  TERMSANDCONDITION:"TERMS & CONDITIONS",
  ACCEPTS:"Accept & Confirm"
    },
  INTROSLIDER:{
    TITLE:"Fresh Seafood",
    SECTITLE:"Exciting Prizes",
    THIRDTITLE:"Fast Delivery",
    CONTENT:"Loream ipsum dolor sit amet.consectetur  adipising edit,sed do eiusmod tempor incididunt ut labore et dolor magna aliqua.",
    FLEXIBLEANDCONVENIENTTITLE:"Flexible & Convenient",
    FLEXIBLEANDCONVENIENTCONTENT:"Skip the queue. Get the advice you need from the comfort of your home instantly. You can also Schedule an appointment with your Preferred Provider at your convenice.",
    MEDICATIONSTOREFFERALSTITLE:"Medications to refferals covered",
    MEDICATIONSTOREFFERALSCONTENT:"Supporting documents will be sent straight to your inbox when necessary and medication delivery is FREE!"
  },
  PLACEHOLDER:{
      NAME:"Name",
      USERNAME:"Email / User ID",
      USERNAME1:"User Name",
      EMAILID:"Email or Phone number",
      BIRTHDATE:"Birthdate",
      GENDER:"Gender",
      CHANGEPWD:"Change Password",
      LOGOUT:"Logout",
      PASSWORD:"Password",
      NEWPASSWORD:"New Password",
      CONFIRMPWD:"Confirm Password",
      CARDNUMBER:"Card Number",
      CARDHOLDERNAME:"Cardholder Name"

     
  },
  UPCOMINGAPPTTEXT:{
    UPCOMINGAPPOINTMENTTITLE:"Upcoming Appointment",
    DCTNAME:"Dr. Dimitri Petrenko",
    NAME:"Name:",
    GENERALPRACTITIONER:"General Practitioner",
    APPOINTMENT:"Appointment:",
    PATIENTDETAILS:"Patient Details",
    ID:"ID#1053",
    NAME:"Name:",
    DDOB:"Date of birth:",
    DNRIC:"NRIC/Passport:",
    RELATIONSHIP:"Relationship:",
    REMAINDER:"Reminder",
    REMAINDERCONTENT:"Please prepare your IC/Passport before the call to show when connected.",
    CANCELAPPTCONTENT:"Your appointment is schedule to be held, you're no longer able to cancel before 30 mins prior to the appointment.",
    CANCELAPPT:"Cancel Appointment",
    SELECT:"Select",
    DID:"Did you change you mind?",
    DIDCONTENT:"It's sad to hear that you want to cancel the appointment, but please tell us why.",
  },
  CONFIRMCONSULATTEXT:{
    CONFIRMCONSULTATION:"Confirm Consultation",
    PAYMENTMETHOD:"Payment Method",
    ADDNOW:"Add Now",
    ADDCARD:"Add Card",
    CARDNO:"Card Number",
    CARDHOLDERNAME:"CARDHOLDER NAME",
    EXPIRY:"Expiry",
    SECURITYCODE:"Security Code",
    SAVEPAYMENTMETHOD:"Save Payment Method",
    VISA:"VISA",
    VALIDTEXT:"VALID THRU",
    CURRENTNO:"Current Queue Number:"

  },
  DRFOUNDTEXT:{
    QUESTION1: '$45/Conulation',
    ANSWER1:"The fee covers a 10-minute video consulation.",
    QUESTION2: 'Does it include medication?',
    ANSWER2:"The cost of medication is not covered",
    QUESTION3: 'When will I be charged?',
    ANSWER3:"Your credit card will only be charged after your consultion call with/without medication."
  },
  CATEGORIES:{
    TITLE:"Categories",
    DIABETES:"Diabetes",
    MYCART:"My Cart",
    SUBTOTAL:"Subtotal",
    DELIVERY:"Delivery Charge",
    TAX:"Discount",
    TOTAL:"Total",
    CHECKOUT:"CHECKOUT",
    PLACE:"Place order",
    ORDERHISTORY:"Orders",
    EDITPROFILE1:"Edit Profile",
    MANAGEADDRESS:"Manage Address",
    PAYMENTTT:"Payment Methods",
    Wallet:"Wallet",
    INVITE:"Invite Friends",
    PAYMENTT:"Payment Method",
    SUCCESSFUL:"Order #1001 Successful",
    ORDERCONTENT:"To check your order summary & shipping status click below.",
    VIEWORDERS:"View Order Summmary",
    ORDER:"Order",
    SHIPPINGDETAILS:"Shipping Details",
    ORDERSUMMARY:"Order Summary",
    PRICE:"Price",
    ORDERTOTAL:"Order Total",
    CONFIRMADDRESS:"Confirm Address",
    ADDADDRESS:"Add Address",
    ADDADDRESS1:"Add New Address",
    PAYMENT11:"Add New Card"
  },
  HEADERTITLE:{
    FILTER:"Filter By",
    PROFILE:"Profile",
    EDIT:"Edit",
    APPLY:"Apply",  
  },
  ALERT: {
      ALERT_OKAY: "Okay",
      ALERT_ERROR: "Error",
      ALERT_SUCCESS: "Success",
      EMPTY_EMAIL: "Please Enter Your Email Address",
      EMPTY_PHONE_NUMBER: "Please Enter Your Phone Number",
      EMPTY_PHONE_NUMBER_INCORRECT: "Phone Number is incorrect",
      EMPTY_PASSWORD: "Please Enter Your Password",
      PASSWORD_INCORRECT: "Password is incorrect",
      PASSWORD_CASESENSITIVE : "Password should be contain atleast one upper case and one lower case and number",
      EMAILINCORRECT: "Email is incorrect",
      EMAILINVALID: "Email Id is invalid",
      EMPTY_NAME : "Please Enter Your Name",   
      EMPTY_USER_NAME : "Please Enter Your Username",   
      EMPTY_CONFIRMPASSWORD : "Please Enter Your Confirm Password",
      PASSWORDLENGTH : "Please Enter Minimum 8 Letters for Password",
      PASSWORD_MISSMATCH : "Password Mismatched",
      PHONENO_INCORRECT:"Mobile Number is incorrect",
      PHONENO_INVALID:"Mobile Number is Invalid",
    },
  MINSLINE:"−",
  PLUSMARK:"+",
  ADDCART:"ADD TO CART",
  PRICETEXT:"PRICE ₹",
  CUSTOMIZE:"CUSTOMIZE",
  CONTINUE:"CONTINUE",
  TOTAL:"TOTAL",  
  PROFILEINFO:"PERSONAL INFO",
  ORDERHIS:"ORDER HISTORY", 
  CHANGEPWD:"Change Password",
  LOGOUT:"Logout",
  AUTHTOKEN:"token",
  
  BOTTOMMENUTITLE :
  { 
  SETTINGS : "Settings",
  WISHLIST : "Wishlist",
  HOME : "Home",
  MYCART : "My cart",
  PROFILE : "Profile"
  },
  

}